version: 2
updates:
  # Dev Branch Configuration
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
    allow:
      - dependency-type: direct
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      # Update all dependencies except pressbooks/* (dev)
      all-except-pressbooks-dev:
        patterns:
          - "*"
        exclude-patterns:
          - "pressbooks/*"